services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_plea_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: devuser
      DB_PASSWORD: devpassword
      DB_DATABASE: student_plea_db
    depends_on:
      - mysql
    networks:
      - student-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - student-network

volumes:
  mysql_data:

networks:
  student-network:
    driver: bridge