FROM node:18.18.2

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g npm@latest && \
    npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]